### ISSUE TITLE
Capitalization issue

### ISSUE THREAD

**Issue by ShadowNinja** [CasimirKaPazi/vortoj#14]
Currently the translation files have all-caps language codes and init.lua checks for then case-sensitively.  This should work on case-insensitive fileyestem implementations (eg, HFS+, Windows's default NTFS API, and the FAT family I think) but will fail on all others if the code doesn't happen to be all caps in the config (and it's usually lowercase).

Init.lua should use string.upper() to ensure the case doesn't matter.

**Comment by CasimirKaPazi** [comment]
Thanks for pointing this out. It's included now.
