### ISSUE TITLE
Translations license?

### ISSUE THREAD

**Issue by LNJ2** [CasimirKaPazi/vortoj#17]
There should be a notice how you can use the translations. Or is it the same license as the code (GPLv3)? (Then I can't use it for https://github.com/minetest-mods/mtg_i18n)

**Comment by CasimirKaPazi** [comment]
Yes, that's a problem (my fault). I have no idea if I can add a license now or if I would have to ask everyone who contributed.

I would prefer CC0 or similar.

**Comment by LNJ2** [comment]
I think, if you ask them you can do everything. CC0 would be nice.

**Comment by CasimirKaPazi** [comment]
I now added a note in the README and listed all translations with unclear license (currently all).

To change the translations to CC0 I would like to ask everyone who contributed to answer here wether or not they are okay with it.
Asking: @Wuzzy2 @Enki4 @AetherSeed @mahmutelmas06 @larjona @srifqi 
Oliver Migeot (FR) and Rui914 (JA) don't have a github account any more.

**Comment by HybridDog** [comment]
https://github.com/Rui-Minetest

**Comment by Wuzzy2** [comment]
Do whatever you want. CC0 is fine.

**Comment by larjona** [comment]
El 27 de mayo de 2017 21:33:57 CEST, Casimir <notifications@github.com> escribió:
>I now added a note in the README and listed all translations with
>unclear license (currently all).
>
>To change the translations to CC0 I would like to ask everyone who
>contributed to answer here wether or not they are okay with it.
>Asking: @Wuzzy2 @Enki4 @AetherSeed @mahmutelmas06 @larjona @srifqi 
>Oliver Migeot (FR) and Rui914 (JA) don't have a github account any
>more.

Hi
I thought translations inherited the software license.
CC0 or any other free/open source license is ok for me.
Thanks for caring!
Laura Arjona Reina
https://wiki.debian.org/LauraArjona

**Comment by Wuzzy2** [comment]
>  I thought translations inherited the software license.

Please go with this assumption.

**Comment by mahmutelmas06** [comment]
it is ok for me

**Comment by AetherSeed** [comment]
All fine by me. I don't recall having contributed to that translation in the end so please feel free to remove me from the list of translators entirely.
________________________________

**Comment by srifqi** [comment]
Same as @larjona, The translation should be the same license as the main software.

But, I'm okay with CC0.

**Comment by LNJ2** [comment]
Thank you! :smiley: 
I converted your translations to po-files and added them to my [Minetest Game Internationalization Mod](https://github.com/minetest-mods/mtg_i18n).

https://github.com/minetest-mods/mtg_i18n/commit/c4105540d02fb67f4137e4c9ec546bb64c907400 French
https://github.com/minetest-mods/mtg_i18n/commit/28a5fadb2b21cbc66d998fd964b5d64ab0831b2d Indonesian
https://github.com/minetest-mods/mtg_i18n/commit/e24ec1af196d9f19ec7bc983163f5ce5e26b4e8e Italian
https://github.com/minetest-mods/mtg_i18n/commit/b62801aa8eb4e0a0c57e1c45c6b23bf2a64642c0 Japanese

But as you can see on [Weblate](https://hosted.weblate.org/projects/minetest/mtg_i18n/) they aren't in a good state anymore, so it would be very nice if you could help completing them again (anyone can translate on weblate).
